INSERT INTO test (name, code) VALUES ('Afghanistan', 'AF')
INSERT INTO test (name, code) VALUES ('Åland Islands', 'AX')
INSERT INTO test (name, code) VALUES ('Albania', 'AL')
INSERT INTO test (name, code) VALUES ('Algeria', 'DZ')
INSERT INTO test (name, code) VALUES ('American Samoa', 'AS')
INSERT INTO test (name, code) VALUES ('AndorrA', 'AD')
INSERT INTO test (name, code) VALUES ('Angola', 'AO')
INSERT INTO test (name, code) VALUES ('Anguilla', 'AI')
INSERT INTO test (name, code) VALUES ('Antarctica', 'AQ')
INSERT INTO test (name, code) VALUES ('Antigua and Barbuda', 'AG')
INSERT INTO test (name, code) VALUES ('Argentina', 'AR')
INSERT INTO test (name, code) VALUES ('Armenia', 'AM')
INSERT INTO test (name, code) VALUES ('Aruba', 'AW')
INSERT INTO test (name, code) VALUES ('Australia', 'AU')
INSERT INTO test (name, code) VALUES ('Austria', 'AT')
INSERT INTO test (name, code) VALUES ('Azerbaijan', 'AZ')
INSERT INTO test (name, code) VALUES ('Bahamas', 'BS')
INSERT INTO test (name, code) VALUES ('Bahrain', 'BH')
INSERT INTO test (name, code) VALUES ('Bangladesh', 'BD')
INSERT INTO test (name, code) VALUES ('Barbados', 'BB')
INSERT INTO test (name, code) VALUES ('Belarus', 'BY')
INSERT INTO test (name, code) VALUES ('Belgium', 'BE')
INSERT INTO test (name, code) VALUES ('Belize', 'BZ')
INSERT INTO test (name, code) VALUES ('Benin', 'BJ')
INSERT INTO test (name, code) VALUES ('Bermuda', 'BM')
INSERT INTO test (name, code) VALUES ('Bhutan', 'BT')
INSERT INTO test (name, code) VALUES ('Bolivia', 'BO')
INSERT INTO test (name, code) VALUES ('Bosnia and Herzegovina', 'BA')
INSERT INTO test (name, code) VALUES ('Botswana', 'BW')
INSERT INTO test (name, code) VALUES ('Bouvet Island', 'BV')
INSERT INTO test (name, code) VALUES ('Brazil', 'BR')
INSERT INTO test (name, code) VALUES ('British Indian Ocean Territory', 'IO')
INSERT INTO test (name, code) VALUES ('Brunei Darussalam', 'BN')
INSERT INTO test (name, code) VALUES ('Bulgaria', 'BG')
INSERT INTO test (name, code) VALUES ('Burkina Faso', 'BF')
INSERT INTO test (name, code) VALUES ('Burundi', 'BI')
INSERT INTO test (name, code) VALUES ('Cambodia', 'KH')
INSERT INTO test (name, code) VALUES ('Cameroon', 'CM')
INSERT INTO test (name, code) VALUES ('Canada', 'CA')
INSERT INTO test (name, code) VALUES ('Cape Verde', 'CV')
INSERT INTO test (name, code) VALUES ('Cayman Islands', 'KY')
INSERT INTO test (name, code) VALUES ('Central African Republic', 'CF')
INSERT INTO test (name, code) VALUES ('Chad', 'TD')
INSERT INTO test (name, code) VALUES ('Chile', 'CL')
INSERT INTO test (name, code) VALUES ('China', 'CN')
INSERT INTO test (name, code) VALUES ('Christmas Island', 'CX')
INSERT INTO test (name, code) VALUES ('Cocos (Keeling) Islands', 'CC')
INSERT INTO test (name, code) VALUES ('Colombia', 'CO')
INSERT INTO test (name, code) VALUES ('Comoros', 'KM')
INSERT INTO test (name, code) VALUES ('Congo', 'CG')
INSERT INTO test (name, code) VALUES ('Congo, The Democratic Republic of the', 'CD')
INSERT INTO test (name, code) VALUES ('Cook Islands', 'CK')
INSERT INTO test (name, code) VALUES ('Costa Rica', 'CR')
INSERT INTO test (name, code) VALUES ('Cote D'Ivoire', 'CI')
INSERT INTO test (name, code) VALUES ('Croatia', 'HR')
INSERT INTO test (name, code) VALUES ('Cuba', 'CU')
INSERT INTO test (name, code) VALUES ('Cyprus', 'CY')
INSERT INTO test (name, code) VALUES ('Czech Republic', 'CZ')
INSERT INTO test (name, code) VALUES ('Denmark', 'DK')
INSERT INTO test (name, code) VALUES ('Djibouti', 'DJ')
INSERT INTO test (name, code) VALUES ('Dominica', 'DM')
INSERT INTO test (name, code) VALUES ('Dominican Republic', 'DO')
INSERT INTO test (name, code) VALUES ('Ecuador', 'EC')
INSERT INTO test (name, code) VALUES ('Egypt', 'EG')
INSERT INTO test (name, code) VALUES ('El Salvador', 'SV')
INSERT INTO test (name, code) VALUES ('Equatorial Guinea', 'GQ')
INSERT INTO test (name, code) VALUES ('Eritrea', 'ER')
INSERT INTO test (name, code) VALUES ('Estonia', 'EE')
INSERT INTO test (name, code) VALUES ('Ethiopia', 'ET')
INSERT INTO test (name, code) VALUES ('Falkland Islands (Malvinas)', 'FK')
INSERT INTO test (name, code) VALUES ('Faroe Islands', 'FO')
INSERT INTO test (name, code) VALUES ('Fiji', 'FJ')
INSERT INTO test (name, code) VALUES ('Finland', 'FI')
INSERT INTO test (name, code) VALUES ('France', 'FR')
INSERT INTO test (name, code) VALUES ('French Guiana', 'GF')
INSERT INTO test (name, code) VALUES ('French Polynesia', 'PF')
INSERT INTO test (name, code) VALUES ('French Southern Territories', 'TF')
INSERT INTO test (name, code) VALUES ('Gabon', 'GA')
INSERT INTO test (name, code) VALUES ('Gambia', 'GM')
INSERT INTO test (name, code) VALUES ('Georgia', 'GE')
INSERT INTO test (name, code) VALUES ('Germany', 'DE')
INSERT INTO test (name, code) VALUES ('Ghana', 'GH')
INSERT INTO test (name, code) VALUES ('Gibraltar', 'GI')
INSERT INTO test (name, code) VALUES ('Greece', 'GR')
INSERT INTO test (name, code) VALUES ('Greenland', 'GL')
INSERT INTO test (name, code) VALUES ('Grenada', 'GD')
INSERT INTO test (name, code) VALUES ('Guadeloupe', 'GP')
INSERT INTO test (name, code) VALUES ('Guam', 'GU')
INSERT INTO test (name, code) VALUES ('Guatemala', 'GT')
INSERT INTO test (name, code) VALUES ('Guernsey', 'GG')
INSERT INTO test (name, code) VALUES ('Guinea', 'GN')
INSERT INTO test (name, code) VALUES ('Guinea-Bissau', 'GW')
INSERT INTO test (name, code) VALUES ('Guyana', 'GY')
INSERT INTO test (name, code) VALUES ('Haiti', 'HT')
INSERT INTO test (name, code) VALUES ('Heard Island and Mcdonald Islands', 'HM')
INSERT INTO test (name, code) VALUES ('Holy See (Vatican City State)', 'VA')
INSERT INTO test (name, code) VALUES ('Honduras', 'HN')
INSERT INTO test (name, code) VALUES ('Hong Kong', 'HK')
INSERT INTO test (name, code) VALUES ('Hungary', 'HU')
INSERT INTO test (name, code) VALUES ('Iceland', 'IS')
INSERT INTO test (name, code) VALUES ('India', 'IN')
INSERT INTO test (name, code) VALUES ('Indonesia', 'ID')
INSERT INTO test (name, code) VALUES ('Iran, Islamic Republic Of', 'IR')
INSERT INTO test (name, code) VALUES ('Iraq', 'IQ')
INSERT INTO test (name, code) VALUES ('Ireland', 'IE')
INSERT INTO test (name, code) VALUES ('Isle of Man', 'IM')
INSERT INTO test (name, code) VALUES ('Israel', 'IL')
INSERT INTO test (name, code) VALUES ('Italy', 'IT')
INSERT INTO test (name, code) VALUES ('Jamaica', 'JM')
INSERT INTO test (name, code) VALUES ('Japan', 'JP')
INSERT INTO test (name, code) VALUES ('Jersey', 'JE')
INSERT INTO test (name, code) VALUES ('Jordan', 'JO')
INSERT INTO test (name, code) VALUES ('Kazakhstan', 'KZ')
INSERT INTO test (name, code) VALUES ('Kenya', 'KE')
INSERT INTO test (name, code) VALUES ('Kiribati', 'KI')
INSERT INTO test (name, code) VALUES ('Korea, Democratic People'S Republic of', 'KP')
INSERT INTO test (name, code) VALUES ('Korea, Republic of', 'KR')
INSERT INTO test (name, code) VALUES ('Kuwait', 'KW')
INSERT INTO test (name, code) VALUES ('Kyrgyzstan', 'KG')
INSERT INTO test (name, code) VALUES ('Lao People's Democratic Republic', 'LA')
INSERT INTO test (name, code) VALUES ('Latvia', 'LV')
INSERT INTO test (name, code) VALUES ('Lebanon', 'LB')
INSERT INTO test (name, code) VALUES ('Lesotho', 'LS')
INSERT INTO test (name, code) VALUES ('Liberia', 'LR')
INSERT INTO test (name, code) VALUES ('Libyan Arab Jamahiriya', 'LY')
INSERT INTO test (name, code) VALUES ('Liechtenstein', 'LI')
INSERT INTO test (name, code) VALUES ('Lithuania', 'LT')
INSERT INTO test (name, code) VALUES ('Luxembourg', 'LU')
INSERT INTO test (name, code) VALUES ('Macao', 'MO')
INSERT INTO test (name, code) VALUES ('Macedonia, The Former Yugoslav Republic of', 'MK')
INSERT INTO test (name, code) VALUES ('Madagascar', 'MG')
INSERT INTO test (name, code) VALUES ('Malawi', 'MW')
INSERT INTO test (name, code) VALUES ('Malaysia', 'MY')
INSERT INTO test (name, code) VALUES ('Maldives', 'MV')
INSERT INTO test (name, code) VALUES ('Mali', 'ML')
INSERT INTO test (name, code) VALUES ('Malta', 'MT')
INSERT INTO test (name, code) VALUES ('Marshall Islands', 'MH')
INSERT INTO test (name, code) VALUES ('Martinique', 'MQ')
INSERT INTO test (name, code) VALUES ('Mauritania', 'MR')
INSERT INTO test (name, code) VALUES ('Mauritius', 'MU')
INSERT INTO test (name, code) VALUES ('Mayotte', 'YT')
INSERT INTO test (name, code) VALUES ('Mexico', 'MX')
INSERT INTO test (name, code) VALUES ('Micronesia, Federated States of', 'FM')
INSERT INTO test (name, code) VALUES ('Moldova, Republic of', 'MD')
INSERT INTO test (name, code) VALUES ('Monaco', 'MC')
INSERT INTO test (name, code) VALUES ('Mongolia', 'MN')
INSERT INTO test (name, code) VALUES ('Montserrat', 'MS')
INSERT INTO test (name, code) VALUES ('Morocco', 'MA')
INSERT INTO test (name, code) VALUES ('Mozambique', 'MZ')
INSERT INTO test (name, code) VALUES ('Myanmar', 'MM')
INSERT INTO test (name, code) VALUES ('Namibia', 'NA')
INSERT INTO test (name, code) VALUES ('Nauru', 'NR')
INSERT INTO test (name, code) VALUES ('Nepal', 'NP')
INSERT INTO test (name, code) VALUES ('Netherlands', 'NL')
INSERT INTO test (name, code) VALUES ('Netherlands Antilles', 'AN')
INSERT INTO test (name, code) VALUES ('New Caledonia', 'NC')
INSERT INTO test (name, code) VALUES ('New Zealand', 'NZ')
INSERT INTO test (name, code) VALUES ('Nicaragua', 'NI')
INSERT INTO test (name, code) VALUES ('Niger', 'NE')
INSERT INTO test (name, code) VALUES ('Nigeria', 'NG')
INSERT INTO test (name, code) VALUES ('Niue', 'NU')
INSERT INTO test (name, code) VALUES ('Norfolk Island', 'NF')
INSERT INTO test (name, code) VALUES ('Northern Mariana Islands', 'MP')
INSERT INTO test (name, code) VALUES ('Norway', 'NO')
INSERT INTO test (name, code) VALUES ('Oman', 'OM')
INSERT INTO test (name, code) VALUES ('Pakistan', 'PK')
INSERT INTO test (name, code) VALUES ('Palau', 'PW')
INSERT INTO test (name, code) VALUES ('Palestinian Territory, Occupied', 'PS')
INSERT INTO test (name, code) VALUES ('Panama', 'PA')
INSERT INTO test (name, code) VALUES ('Papua New Guinea', 'PG')
INSERT INTO test (name, code) VALUES ('Paraguay', 'PY')
INSERT INTO test (name, code) VALUES ('Peru', 'PE')
INSERT INTO test (name, code) VALUES ('Philippines', 'PH')
INSERT INTO test (name, code) VALUES ('Pitcairn', 'PN')
INSERT INTO test (name, code) VALUES ('Poland', 'PL')
INSERT INTO test (name, code) VALUES ('Portugal', 'PT')
INSERT INTO test (name, code) VALUES ('Puerto Rico', 'PR')
INSERT INTO test (name, code) VALUES ('Qatar', 'QA')
INSERT INTO test (name, code) VALUES ('Reunion', 'RE')
INSERT INTO test (name, code) VALUES ('Romania', 'RO')
INSERT INTO test (name, code) VALUES ('Russian Federation', 'RU')
INSERT INTO test (name, code) VALUES ('RWANDA', 'RW')
INSERT INTO test (name, code) VALUES ('Saint Helena', 'SH')
INSERT INTO test (name, code) VALUES ('Saint Kitts and Nevis', 'KN')
INSERT INTO test (name, code) VALUES ('Saint Lucia', 'LC')
INSERT INTO test (name, code) VALUES ('Saint Pierre and Miquelon', 'PM')
INSERT INTO test (name, code) VALUES ('Saint Vincent and the Grenadines', 'VC')
INSERT INTO test (name, code) VALUES ('Samoa', 'WS')
INSERT INTO test (name, code) VALUES ('San Marino', 'SM')
INSERT INTO test (name, code) VALUES ('Sao Tome and Principe', 'ST')
INSERT INTO test (name, code) VALUES ('Saudi Arabia', 'SA')
INSERT INTO test (name, code) VALUES ('Senegal', 'SN')
INSERT INTO test (name, code) VALUES ('Serbia and Montenegro', 'CS')
INSERT INTO test (name, code) VALUES ('Seychelles', 'SC')
INSERT INTO test (name, code) VALUES ('Sierra Leone', 'SL')
INSERT INTO test (name, code) VALUES ('Singapore', 'SG')
INSERT INTO test (name, code) VALUES ('Slovakia', 'SK')
INSERT INTO test (name, code) VALUES ('Slovenia', 'SI')
INSERT INTO test (name, code) VALUES ('Solomon Islands', 'SB')
INSERT INTO test (name, code) VALUES ('Somalia', 'SO')
INSERT INTO test (name, code) VALUES ('South Africa', 'ZA')
INSERT INTO test (name, code) VALUES ('South Georgia and the South Sandwich Islands', 'GS')
INSERT INTO test (name, code) VALUES ('Spain', 'ES')
INSERT INTO test (name, code) VALUES ('Sri Lanka', 'LK')
INSERT INTO test (name, code) VALUES ('Sudan', 'SD')
INSERT INTO test (name, code) VALUES ('Suriname', 'SR')
INSERT INTO test (name, code) VALUES ('Svalbard and Jan Mayen', 'SJ')
INSERT INTO test (name, code) VALUES ('Swaziland', 'SZ')
INSERT INTO test (name, code) VALUES ('Sweden', 'SE')
INSERT INTO test (name, code) VALUES ('Switzerland', 'CH')
INSERT INTO test (name, code) VALUES ('Syrian Arab Republic', 'SY')
INSERT INTO test (name, code) VALUES ('Taiwan, Province of China', 'TW')
INSERT INTO test (name, code) VALUES ('Tajikistan', 'TJ')
INSERT INTO test (name, code) VALUES ('Tanzania, United Republic of', 'TZ')
INSERT INTO test (name, code) VALUES ('Thailand', 'TH')
INSERT INTO test (name, code) VALUES ('Timor-Leste', 'TL')
INSERT INTO test (name, code) VALUES ('Togo', 'TG')
INSERT INTO test (name, code) VALUES ('Tokelau', 'TK')
INSERT INTO test (name, code) VALUES ('Tonga', 'TO')
INSERT INTO test (name, code) VALUES ('Trinidad and Tobago', 'TT')
INSERT INTO test (name, code) VALUES ('Tunisia', 'TN')
INSERT INTO test (name, code) VALUES ('Turkey', 'TR')
INSERT INTO test (name, code) VALUES ('Turkmenistan', 'TM')
INSERT INTO test (name, code) VALUES ('Turks and Caicos Islands', 'TC')
INSERT INTO test (name, code) VALUES ('Tuvalu', 'TV')
INSERT INTO test (name, code) VALUES ('Uganda', 'UG')
INSERT INTO test (name, code) VALUES ('Ukraine', 'UA')
INSERT INTO test (name, code) VALUES ('United Arab Emirates', 'AE')
INSERT INTO test (name, code) VALUES ('United Kingdom', 'GB')
INSERT INTO test (name, code) VALUES ('United States', 'US')
INSERT INTO test (name, code) VALUES ('United States Minor Outlying Islands', 'UM')
INSERT INTO test (name, code) VALUES ('Uruguay', 'UY')
INSERT INTO test (name, code) VALUES ('Uzbekistan', 'UZ')
INSERT INTO test (name, code) VALUES ('Vanuatu', 'VU')
INSERT INTO test (name, code) VALUES ('Venezuela', 'VE')
INSERT INTO test (name, code) VALUES ('Viet Nam', 'VN')
INSERT INTO test (name, code) VALUES ('Virgin Islands, British', 'VG')
INSERT INTO test (name, code) VALUES ('Virgin Islands, U.S.', 'VI')
INSERT INTO test (name, code) VALUES ('Wallis and Futuna', 'WF')
INSERT INTO test (name, code) VALUES ('Western Sahara', 'EH')
INSERT INTO test (name, code) VALUES ('Yemen', 'YE')
INSERT INTO test (name, code) VALUES ('Zambia', 'ZM')
INSERT INTO test (name, code) VALUES ('Zimbabwe', 'ZW')